title: Gervoeur
remote_theme: oisiflorus/maquillage-danslajungle

defaults:
  - scope:
      path: ""
    values:
      layout: location

collections_dir: Les écrits de Georgina

collections:
  Elles et Ils... mon archipel:
    output: true
  Elles et Ils... mon archipel:
    output: true
  Elles et Ils... mon archipel:
    output: true
  
plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-titles-from-headings
