title: Gervoeur
remote_theme: oisiflorus/maquillage-danslajungle

defaults:
  - scope:
      path: ""
    values:
      layout: location


navbar-links:
  Archives:
    - <2020>: "archives2020"
    - <2019>: "archives2019"
    - <2018>: "archives2018"
  # Associations: "https://associations.amzer.bzh"
  Contact: "contact" 
  Surprise: "404" 
  # Author's home: "https://deanattali.com"

collections_dir: Les écrits de Georgina

collections:
  Elles et Ils... mon archipel:
    output: true
  Elles et Ils... mon archipel:
    output: true
  Elles et Ils... mon archipel:
    output: true
  
plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-titles-from-headings
